Fixed a bug when restoring master cuts in strong branching
atoptima/Coluna.jl pull request #444
Opened 2021-02-06 21:03 UTC by artalvpes

Note: I have added several (disabled) debugging tools used to find the bug.

2021-02-08 08:23 UTC, rrsadykov reviewed
Artur, can you explain how your debugging tools work?

2021-02-08 08:23 UTC, rrsadykov commented on src/Algorithm/branching/branchingalgo.jl
> -        end
Artur, why did you remove this?

2021-02-08 08:23 UTC, rrsadykov commented on src/Algorithm/basic/cutcallback.jl
> +    ) where {Duty<:MathProg.AbstractFormDuty}
Nice! Sorry for this bug.

2021-02-08 08:23 UTC, rrsadykov commented on src/Coluna.jl
> +macro debug()
Is it possible to add a debug parameter and a test to cover these debug functions.

2021-02-08 08:46 UTC, guimarqu commented on src/Coluna.jl
> +macro debug()
The debug tool should not stay in the code otherwise we need to test it. Can we move it to the documentation ?

2021-02-08 08:48 UTC, guimarqu commented on src/Algorithm/basic/solvelpform.jl
> +    # MOI.set(form.optimizer.inner, MOI.RawParameter("Method"), 2)
Can we remove these comments ?

2021-02-08 08:48 UTC, guimarqu commented on src/MOIcallbacks.jl
> +        form, "", MasterBendCutConstr; #TODO: Create a specific type for user cuts
Why did you change the duty ?

2021-02-09 11:58 UTC, artalvpes commented on src/Algorithm/branching/branchingalgo.jl
> -        end
Hi Ruslan. I think it had no effect. Did you intend to use = instead of == ?

2021-02-09 12:00 UTC, artalvpes commented on src/Coluna.jl
> +macro debug()
No problem. I just did not want to loose it.

2021-02-09 12:00 UTC, artalvpes commented on src/Algorithm/basic/solvelpform.jl
> +    # MOI.set(form.optimizer.inner, MOI.RawParameter("Method"), 2)
No problem.

2021-02-09 12:07 UTC, artalvpes commented on src/MOIcallbacks.jl
> +        form, "", MasterBendCutConstr; #TODO: Create a specific type for user cuts
This is important. I had to fix two things to make it work. This is one of them. The user cuts were not being recognized by the constructor of MasterCutsState because of the condition "getduty(id) <= AbstractMasterCutConstr" and I did not want to change the complex hierarchy defined in "duties.jl". So defining it as a MasterBendCutConstr was a solution with minimum changes to avoid generating new bugs.

2021-02-09 12:12 UTC, artalvpes commented on src/Algorithm/branching/branchingalgo.jl
> -        end
Anyway, we decided to let the nodes survive a little bit more before being deleted to let them appear in the branch tree file. We don't think there will be a significant impact in the performance.

2021-02-09 12:35 UTC, artalvpes commented
I think it is worth letting a general comment about the code structure here. I think it would help a lot for people that starts looking at the code if there was a more clearly marked standard structure for the storages that were followed by all algorithms. Perhaps we could put each algorithm and each storage type in a separate file and force all storage functions to be redefined (like get_storages_usage and get_child_algorithms) even if they do nothing (by generating an error message in the function that receives the abstract type). Calls to restore_states!, store_states! and remove_states! could perhaps be more emphasised and/or we could try to keep them in the first call level (function run!) of their algorithms.

2021-02-09 13:17 UTC, rrsadykov commented on src/Algorithm/branching/branchingalgo.jl
> -        end
Yes, it should be =.  This is needed to avoid unnecessary evaluation of branching candidates, when one of candidates is already conquered.

2021-02-09 13:22 UTC, rrsadykov commented
I agree that we need a document describing the architecture of Coluna (environment, models, formulations, algorithms, storages, and other concepts we use). Guillaume should have started such a document. I will review and complete it when Guillaume is done with his part.  A link to this document should be in the README.md file.

2021-02-09 15:28 UTC, artalvpes commented on src/Algorithm/branching/branchingalgo.jl
> -        end
I suggest marking it as conquered and testing it in the beginning of the evaluation to avoid evaluating it again but letting it persist until being written to the branch tree file (equivalent to BaPTree.dot). Otherwise some nodes will appear with only one child.

2021-02-09 15:53 UTC, rrsadykov commented on src/Algorithm/branching/branchingalgo.jl
> -        end
I did not completely get your point. Branching candidate (group) here is not a child node, but a complete set of child nodes (left branch and right branch).  The group is already marked as conquered and will not be evaluated again.  This is to avoid passing other candidates (or groups) to the next strong branching phase. Thus we avoid evaluating them. This evaluation is not needed as there exists a conquered branching candidate, i.e. all children nodes are conquered. We pass only this branching candidate, and all child nodes of this candidate will appear in the branch tree file.

2021-02-09 16:29 UTC, artalvpes commented on src/Algorithm/branching/branchingalgo.jl
> -        end
Ah! ok. Got it. So, we should put the code back with = replacing ==.

2021-02-10 18:54 UTC, guimarqu requested changes
One style issue to address and then the PR is ready to be merged.

2021-02-10 18:54 UTC, guimarqu commented on src/Algorithm/storage.jl
> +function Base.show(io::IO, stoUsaDict::StoragesUsageDict)
Variable name must be lower case.

2021-02-11 21:12 UTC, guimarqu approved these changes

2021-02-11 21:31 UTC, merged