Essential cut (lazy constraint) generation
atoptima/Coluna.jl pull request #452
Opened 2021-02-25 21:39 UTC by guimarqu

Essential cut gen is performed :

[x] in the cut callback algorithm
[x] each time the colgen algorithm finds an integer solution
[ ] after restricted master heuristic

for colgen : when the cut violates the solution, the colgen restarts at phase 3 if it was at phase 3 and at phase 1 if it was at phase 1 or 2

2021-02-25 23:28 UTC, guimarqu commented
I think it's wrong, it should restart at phase 2 in colgen because it never does essential cutgen at phase 1. I'll fix tomorrow.

2021-02-26 08:15 UTC, rrsadykov requested changes

2021-02-26 08:15 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +                return true, false
Is there a way to make it explicit here what "true" means and what "false" means (to increase the code readability)

2021-02-26 08:15 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +                    cutgen = CutCallbacks(call_robust_facultative = false)
Colgen should indicate that it uses another child algorithm (CutCallbacks) here:

`function get_child_algorithms(algo::ColumnGeneration, reform::Reformulation) `

Moreover, it would be nice if we indicate this only if at least one lazy cut callback is defined.
For this, I suggest to transform CutCallbacks to CutCallback which separates only one family of cuts. CutCallback would now whether it is lazy or facultative and its priority. Then every algorithm which uses cut separation (ColCutGenConquer and ColumnGeneration) should have a vector of CutCallback as a parameter. Then, there will be no overhead if no cut callbacks are defined. And it would be more flexible as priorities would allow us to separate "light" cut before "heavy" ones using priorities

2021-02-26 08:41 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +                return true, false
Ok I'm going to add a comment to describe the method.

2021-02-26 08:47 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +                    cutgen = CutCallbacks(call_robust_facultative = false)
Ok for the first point. I'll fix. 

The second point sounds good, but it's a quite big refactoring so let's do it after we stabilize architecture of algorithms (you can open an issue with a link to your comment).

2021-02-27 09:06 UTC, rrsadykov approved these changes

2021-02-27 09:38 UTC, merged