Rename Storage -> Record
atoptima/Coluna.jl pull request #471
Opened 2021-03-18 16:12 UTC by guimarqu

2021-03-18 21:39 UTC, guimarqu commented
@rrsadykov  ready for review.

2021-03-19 08:53 UTC, rrsadykov requested changes

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/basic/solveipform.jl
> +    # we use records in the read only mode, as all modifications
records -> units

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/branching/branchingalgo.jl
> +# StrongBranching does not use any unit itself,
When we use "unit" in the comments, we can say explicitely "storage unit"

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/branching/branchingalgo.jl
>                  remove_states!(node.stateids)
remove_states should be remove_records, "stateids" should be "recordids" or "records"

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/branching/branchingrule.jl
> +# branching rules are always manager algorithms (they manage storing and restoring units)
Here again it is better to say explicitly "storage units"

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/branching/branchingrule.jl
>      Input of a branching rule (branching separation algorithm)
Input -> Output

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/branching/branchingrule.jl
> +    Contains current incumbents, infeasibility status, and the record of its unit.
Description does not correspond to the structure BranchingRuleOutput

Should be "Contains the branching candidates generated and the updated local id value"

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/branching/varbranching.jl
> +    restore_states!(copy_states(parent.stateids), units_to_restore)
copy_states -> copy_records

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/branching/varbranching.jl
> +    restore_states!(copy_states(parent.stateids), units_to_restore)
restore_states! -> restore_using_records!

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/data.jl
> +check_record_states_participation(::AbstractData) = nothing
check_record_states_participation() -> check_records_participation()

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/data.jl
> +        error(string("No record for pair $pair in $(getnicename(data))"))
No record -> No storage unit

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/branching/branchingalgo.jl
> +# StrongBranching does not use any unit itself,
The same applies to all comments

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/formstorages.jl
> +    Used in formulation units
units -> records, the same for ConstrState

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/formstorages.jl
>      in order to store it to the record state and restore it afterwards.
store it to the record state -> store it to a record

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/formstorages.jl
> +    Consists of EmptyUnit and MasterColumnsState.
EmptyUnit -> FormulationUnit, the same change everywhere in this file

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/formstorages.jl
> +function MasterBranchConstrsRecordState(form::Formulation, unit::FormulationUnit)
MasterBranchContrsRecordState -> MasterBranchContrsRecord, the same change should be for every record type

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/interface.jl
> +function initialize_units!(data::AbstractData, algo::AbstractOptimizationAlgorithm)
Here I think we can explicitly call function "initialize_storage_units()"

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/preprocessing.jl
> +    Record for preprocessing. Contains global data: slacks of constraints,
Record -> Storage Unit

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/storage.jl
> +restorefromstate!(model::AbstractModel, record::AbstractStorageUnit, state::AbstractRecordState) =
record:: -> unit::

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/storage.jl
> +        "record type $(typeof(record)), and record state type $(typeof(state))"
record -> unit in two places, record state type -> record type

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/storage.jl
>      StorageContainer
StorageUnitContainer or UnitContainer

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/storage.jl
> +This container keeps storage units and all states which have been
keeps a storage unit and all its records

2021-03-19 08:53 UTC, rrsadykov commented on src/Algorithm/treesearch.jl
> +# function get_units_usage!(
these two commented function should be deleted

2021-03-19 08:53 UTC, rrsadykov commented on src/MathProg/types.jl
> +A formulation should contain a dictionary of storage units
Actually, any model should contain a storage (a dictionary of storage units).

Is there an advantage of having AbstractFormulation, could we derive Formulation and Reformulation directly from AbstractModel? I have an impression that everything defined for AbstractFormulation should be defined for AbstractModel and moved to ColunaBase

2021-03-19 09:22 UTC, guimarqu commented on src/Algorithm/branching/branchingalgo.jl
>                  remove_states!(node.stateids)
Yes I'm going to change this in another PR. I have to rename all `RecordState`.

2021-03-19 09:25 UTC, guimarqu commented on src/Algorithm/branching/varbranching.jl
> +    restore_states!(copy_states(parent.stateids), units_to_restore)
next PR (RecordState -> Record) otherwise the review becomes very difficult.

2021-03-19 09:25 UTC, guimarqu commented on src/Algorithm/branching/varbranching.jl
> +    restore_states!(copy_states(parent.stateids), units_to_restore)
next PR (RecordState -> Record)

2021-03-19 09:25 UTC, guimarqu commented on src/Algorithm/data.jl
> +check_record_states_participation(::AbstractData) = nothing
next PR (RecordState -> Record)

2021-03-19 09:49 UTC, guimarqu commented
I changed comments related to the title of the PR only. I do each task of #330 in a separate PR because otherwise I'll get lost in my changes haha

2021-03-19 09:49 UTC, rrsadykov approved these changes

2021-03-19 09:56 UTC, merged