Rename Record State -> Record
atoptima/Coluna.jl pull request #472
Opened 2021-03-19 10:27 UTC by guimarqu

task for #330

2021-03-19 10:49 UTC, guimarqu commented on src/Algorithm/storage.jl
> +    TO.@timeit Coluna._to "Restore/remove records" begin
@rrsadykov In https://github.com/atoptima/Coluna.jl/pull/471#discussion_r597481067, you suggested to rename this method `restore_using_records!`. Should we change the order of the arguments ? Because it looks like we restore the storage units using the records.

2021-03-19 10:49 UTC, guimarqu commented on src/Algorithm/storage.jl
> +    TO.@timeit Coluna._to "Restore/remove records" begin
Besides, what's the difference between : `restore_using_records!`/`restore_records!`, `restore_from_record!` and `restore_record!` ?

2021-03-19 11:56 UTC, rrsadykov requested changes

2021-03-19 11:56 UTC, rrsadykov commented on src/Algorithm/data.jl
> +function store_records!(data::ReformData, states::RecordsVector)
states -> records
and similar changes below (stateid->recordid)

2021-03-19 11:56 UTC, rrsadykov commented on src/Algorithm/storage.jl
> +mutable struct StorageContainer{M<:AbstractModel, S<:AbstractStorageUnit, SS<:AbstractRecord}
StorageContrainer -> StorageUnitContainer

2021-03-19 11:56 UTC, rrsadykov commented on src/Algorithm/storage.jl
> +This container keeps storage units and all records which have been
storage units -> a storage unit

2021-03-19 11:56 UTC, rrsadykov commented on src/Algorithm/storage.jl
>  function setcurstate!(
In this function state should be changed to record everywhere

2021-03-19 11:56 UTC, rrsadykov commented on src/Algorithm/storage.jl
> +function restore_record!(
Should be changed to restore_from_record!() or restore_state!()

2021-03-19 11:56 UTC, rrsadykov commented on src/Algorithm/storage.jl
> +    storagecont::StorageContainer{M,S,SS}, statecont::RecordContainer{SS}
In this function too, state should be changed to record everywhere

2021-03-19 11:56 UTC, rrsadykov commented on src/Algorithm/storage.jl
> +    TO.@timeit Coluna._to "Restore/remove records" begin
I think it is better to use restore_from_record() and restore_from_records() everywhere, depending whether a single recordId is passed or a vector of them. You can change the order of parameters if you this it is better

2021-03-19 12:04 UTC, rrsadykov requested changes

2021-03-19 12:04 UTC, rrsadykov commented on src/Algorithm/data.jl
> +store_records!(::AbstractData, ::RecordsVector) = nothing
I think that it is better to use everywhere save_record() or save_records() (depending on the context)

2021-03-19 12:04 UTC, rrsadykov commented on src/Algorithm/data.jl
> +store_records!(::AbstractData, ::RecordsVector) = nothing
Or may be even better save_state_to_record() and restore_state_from_record() to be more explicit.

2021-03-20 15:20 UTC, guimarqu commented on src/Algorithm/data.jl
> +store_records!(::AbstractData, ::RecordsVector) = nothing
I think `save_record(s)` sounds good.

2021-03-20 15:21 UTC, guimarqu commented on src/Algorithm/data.jl
> +store_records!(::AbstractData, ::RecordsVector) = nothing
`save_record` instead of `store_record`

2021-03-20 15:33 UTC, rrsadykov approved these changes

2021-03-20 17:32 UTC, merged