Remove code for spMv operation in colgen
atoptima/Coluna.jl pull request #475
Opened 2021-03-22 13:43 UTC by guimarqu

- close #311 
- waiting for release of DynamicSparseArrays v0.4.0 (already implemented https://github.com/atoptima/DynamicSparseArrays.jl/pull/18)

--

**Performance decrease of reduced costs computation** : for the pricing subproblems, we only need to compute the reduced costs of the subproblem representative variables. Here, we iterate over all the non-zero values of the coefficient matrix so we can also compute the reduced cost of each column.

Solutions : 
1. Separate subproblem representative variables from other variables. We maintain them in another matrix. It will need investigation to see what we should do for Benders.
2. Status quo until it becomes critical
3. Other ? It's open to discussion (@artalvpes @rrsadykov  @vitornesello @FD-V)

PS : not urgent.

2021-03-22 13:56 UTC, rrsadykov commented
Actually, `coeffmatrix` for subproblem representative variables is constant during the whole column generation. So, we should retrieve it in the beginning of the column generation, filter it to leave only this subproblem representative variables, and save it locally. Then this matrix is used to calculate the reduced costs on every iteration (thus, reduced costs of columns and representative variables for other subproblems are not calculated). The matrix should be recalculated only when core cuts are added.

2021-03-22 13:59 UTC, rrsadykov commented
As we talked before, it would be good to retrieve reduced costs of columns directly from the LP solver. It should be faster than calculate them from the coefficient matrix as we do now during master clean up.

2021-03-22 15:14 UTC, guimarqu commented
Ok your solution is a much better version of 1. It sounds good to me.

For the master clean up, we can't retrieve reduced costs through MOI (https://github.com/jump-dev/MathOptInterface.jl/issues/776). Hopefully, the sparse matrix sparse vector multiplication should be quite fast and I think that the deletion of the columns will be the bottleneck.

2021-03-22 15:34 UTC, rrsadykov commented
> For the master clean up, we can't retrieve reduced costs through MOI ([jump-dev/MathOptInterface.jl#776](https://github.com/jump-dev/MathOptInterface.jl/issues/776)). Hopefully, the sparse matrix sparse vector multiplication should be quite fast and I think that the deletion of the columns will be the bottleneck.

Ok, if it is not the bottleneck, the reduced cost of a column can be calculated from the dual of its >= 0 lower bound constraint, as they write there.

2021-04-08 16:32 UTC, rrsadykov requested changes
I think you forgot to recalculate `dwsprep_coefmatrix` after adding core cuts

2021-04-08 16:32 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +    p = sortperm(dwspvarids)
Why we sort subproblem variables?

2021-04-08 16:32 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +    redcosts = deepcopy(redcostshelper.perencosts)
Why it is `deepcopy`, not just `copy`, what is the difference?

2021-04-08 16:32 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +    result = transpose(redcostshelper.dwsprep_coefmatrix) * getsol(dualsol)
May be it is better to transpose during pre-computation, and not on every iteration?

2021-04-08 16:32 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +    closefillmode!(dwsprep_coefmatrix)
What `closefillmode!` serves for?

2021-04-08 16:48 UTC, rrsadykov commented
Ok, I saw that you quit `cg_main_loop!` after generating essential cuts, so `dwsprep_coefmatrix` will be updated.

However, I do not understand why you need to interrupt column generation loop after generating cuts?

2021-04-08 17:12 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +    p = sortperm(dwspvarids)
Indeed, it's not useful anymore because the ouput of spMv is a `Dict`.

2021-04-08 17:12 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +    closefillmode!(dwsprep_coefmatrix)
By default, when you fill a matrix of DynamicSparseArrays, all non-zero entries are stored in a buffer (writing the buffer is a constant time operation). Once you finish to fill the matrix, method `closefillemode!` flushes the buffer (complexity is the number of non-zero entries) and after that, a writing operation costs log^2(n) where n is number of non zero coefficients (if I remember well).

2021-04-08 17:12 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +    redcosts = deepcopy(redcostshelper.perencosts)
AFAIK : 
- `copy` is a shallow copy (copy by value for immutable objects & copy by reference for mutable objects).
- `deepcopy` is a copy by value.

2021-04-08 17:12 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +    result = transpose(redcostshelper.dwsprep_coefmatrix) * getsol(dualsol)
It costs nothing

2021-04-15 08:23 UTC, guimarqu commented
> Ok, I saw that you quit `cg_main_loop!` after generating essential cuts, so `dwsprep_coefmatrix` will be updated.
> 
> However, I do not understand why you need to interrupt column generation loop after generating cuts?

Indeed, it does not make sense to restart colgen when it is in phase 1 or 3. I'll investigate in a new PR today.

2021-04-15 14:36 UTC, rrsadykov approved these changes

2021-04-15 14:37 UTC, merged