Bijection StorageUnit -> Record
atoptima/Coluna.jl pull request #518
Opened 2021-04-24 20:02 UTC by guimarqu

Following our discussion to simplify how storages & records work.

- Wrap storage dict
- Bijection storage unit -> record

Task for #330

2021-04-26 13:55 UTC, rrsadykov requested changes

2021-04-26 13:55 UTC, rrsadykov commented on src/ColunaBase/storage.jl
> +record_type(::Type{<:AbstractStorageUnit}) = error("error")
May be we should give a more explicit error?

2021-04-26 13:55 UTC, rrsadykov commented on src/ColunaBase/storage.jl
> +    typepair::UnitType
I do not think we need `typepair` anymore, as we can just use `SU` and `R`. May be we can even remove `R` from the definition of `StorageUnitWrapper`. Does `RecordWrapper{record_type(SU)}` works here instead of `RecordWrapper{R}`?

2021-04-26 13:55 UTC, rrsadykov commented on src/Algorithm/data.jl
>      for (FullType, storagecont) in storagedict
`UnitType` instead of `FullType`, the same in other places too

2021-04-26 13:55 UTC, rrsadykov commented on src/ColunaBase/storage.jl
> +    add_unit_pair_usage!(::UnitsUsageDict, ::AbstractModel, ::UnitType, ::UnitAccessMode)
Should be `add_unit_usage`

2021-04-27 09:02 UTC, guimarqu commented on src/ColunaBase/storage.jl
> +    typepair::UnitType
I agree, I plan to fix this one later because I would like to remove `UnitType` at the same time.

2021-04-27 09:04 UTC, rrsadykov approved these changes

2021-04-27 09:08 UTC, rrsadykov approved these changes

2021-04-27 09:16 UTC, merged