UnitsUsageDict -> UnitsAccess
atoptima/Coluna.jl pull request #522
Opened 2021-05-04 08:54 UTC by guimarqu

Task of #330

2021-05-04 11:54 UTC, rrsadykov requested changes

2021-05-04 11:54 UTC, rrsadykov commented on src/Algorithm/branching/varbranching.jl
>      restore_from_records!(units_to_restore, copy_records(parent.recordids))
`restore_from_records!()` may also take a vector of pairs (model, unit) instead of the vector of triples (only units which will be restored for writing).

2021-05-04 11:54 UTC, rrsadykov commented on src/ColunaBase/storage.jl
> +# """
We need `EmptyRecord` for storage units which are not changed after initialization.

2021-05-04 11:54 UTC, rrsadykov commented on src/ColunaBase/storage.jl
> +#     EmptyRecordWrapper
The same here. `EmptyRecordWrapper` will be needed for empty records.

2021-05-31 09:48 UTC, guimarqu commented on src/ColunaBase/storage.jl
> +# """
I commented because it is not used in the code nor the tests at the moment

2021-05-31 19:19 UTC, guimarqu commented
@rrsadykov Ok I understand your comments but I would to discuss about the permissions and this method first: 

https://github.com/atoptima/Coluna.jl/blob/c6e41a67b6c6ed5e9cabdaa458871aeaf1375ced/src/ColunaBase/storage.jl#L263-L265

I think we can merge this PR in the midtime.

PS: tests pass

2021-06-01 08:18 UTC, rrsadykov approved these changes

2021-06-01 08:58 UTC, merged