Use subproblem representatives in column generation
atoptima/Coluna.jl pull request #552
Opened 2021-07-07 03:22 UTC by laradicp

2021-07-07 17:19 UTC, laradicp commented on src/Algorithm/colgen.jl
> +            red_cost += getperencost(master, varid) * value # check
@rrsadykov could you check if this change is ok? I did it because now current costs of subproblem representatives are updated along with the subproblem variables, therefore the reduced costs were wrong using `getcurcost(master, varid)`.

2021-07-08 09:31 UTC, rrsadykov requested changes

2021-07-09 04:58 UTC, laradicp commented on src/Algorithm/colgen.jl
> +function getrepvars(master::Formulation, spformid::FormId)
Indeed. I expected to use it, but at the end I didn't have to. I might have missed the right use of this. @guimarqu suggested this function, so I left it for discussion.

2021-07-09 04:58 UTC, laradicp commented on src/Algorithm/colgen.jl
> +        for (varid, _) in getvars(spform)
Sorry, I couldn't understand the described interface. Now that I've thought better about these changes, I see that I actually intended to do something like:
```julia
function update_sp_reduced_costs!(spform::Formulation, master::Formulation)
    for (varid, _) in getvars(spform)
        setcurcost!(spform, varid, getcurcost(master, varid))
    end
end

function update_sps_reduced_costs!(reform::Reformulation)
    for (_, spform) in get_dw_pricing_sps(reform)
        update_sp_reduced_costs!(spform, getmaster(reform))
    end
end
```
This is probably not ideal, because I think it doesn't match the interface.

2021-07-09 09:49 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +            push!(perencosts, getcurcost(master, varid))
Yes, we have a problem here. We cannot update current cost of representative master variables with reduced costs, as they are used for different column generation phases. So, we should leave `getcurcost` here. However, we should not update current cost of representative master variables in updatereducedcosts!(), but pass directly `result` to the subproblem through an interface.  This interface can be (defined in ColunaBase)

```Julia
function update_current_costs!(::AbstractModel, repr_vars_red_costs::PackedMemoryArray{VarId, Float64},
                               dualsol::DualSolution)
end
```

Realization of this interface for `Formulation` would be (it should be defined in MathProg/formulation.jl)

```Julia
function update_current_costs!(form::Formulation, repr_vars_red_costs::PackedMemoryArray{VarId, Float64}, 
                               dualsol::DualSolution)
    for (varid, var) in getvars(form)
        setcurcost!(form, varid, get(repr_vars_red_costs, varid, 0.0))
    end
end
```

Then, function `updatereducedcosts!()` in `ColumnGeneration` would be

```Julia
function updatereducedcosts!(
    reform::Reformulation, redcostshelper::ReducedCostsCalculationHelper, dualsol::DualSolution
)
   redcosts = deepcopy(redcostshelper.perencosts)
   result = redcosts - transpose(redcostshelper.dwsprep_coefmatrix) * getsol(dualsol)
   for (_, spform) in get_dw_pricing_sps(reform)
      update_current_costs!(spform, result, dualsol)
   end
end
```

@guimarqu, can you please check the syntax, I am not sure if we can really obtain `result` like this and what is the type of `result`.

2021-07-09 09:52 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +function getrepvars(master::Formulation, spformid::FormId)
You should at least comment this function if it is not used.

2021-07-09 09:53 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +        for (varid, _) in getvars(spform)
Please see my proposition of interface below

2021-07-09 10:02 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +            push!(perencosts, getcurcost(master, varid))
We can rename `update_current_costs!()` by `update_model!()` as not only costs can be updated due to non-robust constraints. Also, `masterdualsol` may include only dual values related to non-robust master constraints. But I am not sure it is worth to filter the dual solution like that.

2021-07-09 10:19 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +            push!(perencosts, getcurcost(master, varid))
Yes that's a problem and in that case, I think the custom subproblem should maintain Coluna subproblem variables. It will avoid us a big refactoring of the decomposition part.

2021-07-09 10:37 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +            push!(perencosts, getcurcost(master, varid))
It is not a problem for me. The solution is just above (we should not store reduced costs in the master formulation and pass them directly to the subproblem).

2021-07-09 12:58 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +            push!(perencosts, getcurcost(master, varid))
Ok yes the subproblem will at least maintain the varids because of the mapping. So you can just implement `setcurcost!(model, varid, value)` in the subproblem solver, you don't need `update_current_costs!`.

2021-07-09 15:43 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +            push!(perencosts, getcurcost(master, varid))
We need a special function to update the subproblem, as not only costs should be updated in general case (because of non-robust constraints). As I mentioned above we can rename `update_current_costs!()` to `update_model!()`

2021-07-10 05:23 UTC, laradicp commented on src/MathProg/formulation.jl
> +    form::Formulation, repr_vars_red_costs::Dict{VarId, Float64}, ::DualSolution
I used `Dict{VarId, Float64}` because `PackedMemoryArray{VarId, Float64}` threw 
```
MethodError: no method matching get(::DynamicSparseArrays.PackedMemoryArray{Coluna.MathProg.VarId, Float64, DynamicSparseArrays.NoPredictor}, ::Coluna.MathProg.VarId, ::Float64)
```
Is that ok?

2021-07-11 07:48 UTC, rrsadykov commented on src/MathProg/formulation.jl
> +    form::Formulation, repr_vars_red_costs::Dict{VarId, Float64}, ::DualSolution
@guimarqu Which type do you suggest to use here? Is there a performance difference between `Dict` and `PackedMemoryArray`?

2021-07-12 16:47 UTC, guimarqu commented on src/MathProg/formulation.jl
> +    form::Formulation, repr_vars_red_costs::Dict{VarId, Float64}, ::DualSolution
It's better to use the `Dict` in that case. Use PMA only if order matters.

2021-07-12 16:47 UTC, guimarqu commented on src/MathProg/formulation.jl
> +function updatemodel!(
I think you can remove this fallback. It should not be in MathProg because it's specific to column generation.

2021-07-12 16:47 UTC, guimarqu commented on src/MathProg/MathProg.jl
> +    updatemodel!
You can remove `updatemodel!`.

2021-07-12 16:47 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +
You can delete this comment.

2021-07-12 16:47 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +            push!(perencosts, getcurcost(master, varid))
Ok to keep  `update_model!` but this method should stay specific to column generation.

2021-07-13 08:27 UTC, rrsadykov requested changes

2021-07-13 08:27 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +    result = transpose(redcostshelper.dwsprep_coefmatrix) * getsol(masterdualsol)
The last change. Now transposition is done every time `updatereducedcosts!()` is called, instead it should be done only once in `ReducedCostsCalculationHelper`, i.e. `redcostshelper.dwsprep_coefmatrix` should be already transposed.

2021-07-13 14:23 UTC, rrsadykov approved these changes

2021-07-14 08:16 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +function updatemodel!(
I don't think we need this callback.
It's better to leave a comment on top of updatemodel!  saying that this method must be redefined is subproblem is a custom model.

2021-07-14 08:20 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +function updatemodel!(
Sorry, it is not clear for me. What is fallback? And what is the difference between fallback and a method which can be redefined?

2021-07-14 13:19 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +function updatemodel!(
A fallback is an implementation of a method you fall in when the method is not defined for a set of arguments. It replaces the ErrorMethod.

2021-07-14 14:00 UTC, guimarqu approved these changes

2021-07-14 14:00 UTC, merged