Give access to the dual solution of the master to the user
atoptima/Coluna.jl pull request #594
Opened 2021-09-04 20:09 UTC by guimarqu

fix #591

2021-09-06 09:30 UTC, rrsadykov commented on src/Algorithm/colgen.jl
> +                set_lp_dual_sol!(cg_optstate, dual_rm_sol)
Is it really necessary to set the primal and dual solution to `cg_optstate` on every column generation iteration? May be ne may do it only at the end of column generation to save time?

2021-09-06 09:41 UTC, rrsadykov commented on src/Algorithm/treesearch.jl
> +    worst_dual_sol_of_pruned_node::Union{Nothing,DualSolution}
I do not understand the purpose of `worst_db_of_pruned_node` and `worst_dual_sol_of_pruned_node`. Why do we need that? Normally, the current dual bound of TreeSearch is computed as the worst dual bound of open nodes.

2021-09-06 10:04 UTC, rrsadykov requested changes
For me, the top algorithm should return only one OptimizationState which contains the best found IP solution and possibly the LP primal and dual solutions for the root (this may be parameterized to save time).

2021-09-06 19:28 UTC, guimarqu commented on src/Algorithm/treesearch.jl
> +    worst_dual_sol_of_pruned_node::Union{Nothing,DualSolution}
I don't know why I did that.

2021-09-06 19:28 UTC, guimarqu commented on src/optimize.jl
> +    # TODO: how to project the master dual solution on the original formulation ?
Ok for me.

2021-09-06 19:31 UTC, guimarqu commented on src/optimize.jl
> +    lp_dual_sol = get_best_lp_dual_sol(algstate)
Ok, I had doubts about what I did and what you suggest, so let's return the dual solution found at the root node.

2021-09-06 19:33 UTC, guimarqu commented on src/Algorithm/colgen.jl
> +                set_lp_dual_sol!(cg_optstate, dual_rm_sol)
I don't think it will change anything for performances. It's just a pointer that you put in the optimisation state.

2021-09-08 07:43 UTC, rrsadykov requested changes

2021-09-08 07:43 UTC, rrsadykov commented on src/Algorithm/treesearch.jl
>          worst_bound = data.worst_db_of_pruned_node
I still do not understand why dual bound of the tree search takes into account dual bounds of pruned nodes? It should be just equal to the worst dual bound of open nodes (or to the primal bound if there are no open nodes)

2021-09-08 08:02 UTC, guimarqu commented on src/Algorithm/treesearch.jl
>          worst_bound = data.worst_db_of_pruned_node
This is something that we should address in a separate PR. I neither don't understand why I did that.

2021-09-08 08:06 UTC, rrsadykov commented on src/Algorithm/treesearch.jl
>          worst_bound = data.worst_db_of_pruned_node
Why separate PR? This is critical issue. It should be addressed before the next release.

2021-09-08 08:38 UTC, guimarqu commented on src/Algorithm/treesearch.jl
>          worst_bound = data.worst_db_of_pruned_node
Because this is not the scope of this PR. There is no rush for the next release.

2021-09-08 08:42 UTC, rrsadykov approved these changes

2021-09-08 09:01 UTC, merged