Add reformulation parser
atoptima/Coluna.jl pull request #745
Opened 2022-11-03 03:14 UTC by eduardovegas

Closes #702 .

2022-11-15 15:20 UTC, guimarqu commented
Do you think you can move this outside Coluna? I think it would be nice to keep it in the tests. I don't know if we can have a kind of `TestUtils` module in the test folder or something else similar.

2022-11-15 17:04 UTC, eduardovegas commented
Would it be better if the parser file in src/ was moved to test/, and add include("parser.jl") in ColunaTests module? Because creating a submodule I'd have to define some constants that are already in ColunaTests and export the functions from the new module.

2022-11-16 11:15 UTC, guimarqu commented
> Would it be better if the parser file in src/ was moved to test/, and add include("parser.jl") in ColunaTests module? Because creating a submodule I'd have to define some constants that are already in ColunaTests and export the functions from the new module.

Sounds good :)

2022-11-24 09:54 UTC, guimarqu commented on test/integration/parser.jl
> +    bounds = []
```suggestion
    names = String[]
    kinds = ClMP.VarKind[]
    duties = ClMP.Duty{ClMP.Variable}[]
    costs = Float64[]
    bounds = Tuple{Float64,Float64}[]
```

2022-11-24 10:22 UTC, guimarqu requested changes
This is a nice PR. Some minor style issues to address.

2022-11-24 10:22 UTC, guimarqu commented on test/parser.jl
> +        sign = first_m[1] === nothing ? "+" : first_m[1] # has a sign
```suggestion
        sign = isnothing(first_m[1]) ? "+" : first_m[1] # has a sign
```

2022-11-24 10:22 UTC, guimarqu commented on test/parser.jl
> +        coeff = first_m[2] === nothing ? "1" : first_m[2] # has a coefficient
```suggestion
        coeff = isnothing(first_m[2]) ? "1" : first_m[2] # has a coefficient
```

2022-11-24 10:22 UTC, guimarqu commented on test/parser.jl
> +            coeff = m[2] === nothing ? "1" : m[2]
```suggestion
            coeff = isnothing(m[2]) ? "1" : m[2]
```

2022-11-24 10:22 UTC, guimarqu commented on test/parser.jl
> +    if m !== nothing
```suggestion
    if !isnothing(m)
```

2022-11-24 10:22 UTC, guimarqu commented on test/parser.jl
> +        end
```suggestion
    if !isnothing(m)
        vars = _get_vars_list(m[4]) # separate variables as "x_1, x_2" into a list [x_1, x_2]
        if !isnothing(m[1]) # has lower bound (nb <= var) or upper bound (nb >= var)
            bound1 = String(m[2])
        end
        if !isnothing(m[5]) # has upper bound (var <= nb) or lower bound (var >= nb)
            bound2 = String(m[6])
        end
```

2022-11-24 10:22 UTC, guimarqu commented on test/parser.jl
> +    if constr !== nothing
```suggestion
    if !isnothing(constr)
```

2022-11-24 10:22 UTC, guimarqu commented on test/parser.jl
> +    if constr !== nothing
```suggestion
    if !isnothing(constr)
```

2022-11-24 10:22 UTC, guimarqu commented on test/parser.jl
> +                    if spform === nothing
```suggestion
                    if isnothing(spform)
```

2022-11-24 10:22 UTC, guimarqu commented on test/parser.jl
> +    #create subproblems constraints in master
This is a very long method. Is it possible to isolate each step in a specific method?

2022-11-24 20:08 UTC, eduardovegas commented on test/parser.jl
> +    #create subproblems constraints in master
Yes!

2022-11-25 08:15 UTC, guimarqu approved these changes
Thanks @eduardovegas!

2022-11-25 08:15 UTC, merged